# Generated by Django 6.0.3 on 2026-03-12 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('error', 'error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('close', models.FloatField(default=0.0)),
                ('ma_short', models.FloatField(default=0.0)),
                ('ma_long', models.FloatField(default=0.0)),
                ('rsi', models.FloatField(default=0.0)),
                ('adx', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('available', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('float_profit', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('cur_pos', models.IntegerField(default=0)),
                ('held_symbols', models.TextField(blank=True, default='无持仓')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('alert_type', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('error', 'error')], default='warn', max_length=16)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dashboard.strategysnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
